apiVersion: v1
kind: Service
metadata:
  name: monitoramento-alertmanager
  namespace: prometheus
  labels:
    k8s-app: alertmanager
    app.kubernetes.io/name: monitoramento
    app.kubernetes.io/component: alertmanager
spec:
  ports:
  - name: http-port
    port: 9093
    targetPort: 9093
    protocol: TCP
  selector:
    k8s-app: alertmanager
  sessionAffinity: None
  type: ClusterIP

# apiVersion: v1
# kind: Service
# metadata:
#   name: monitoramento-alertmanager
#   labels:
#     k8s-app: alertmanager
#     app.kubernetes.io/name: monitoramento
#     app.kubernetes.io/component: alertmanager
# spec:
#   ports:
#     - name: http
#       # Exposes port 9093 at a cluster-internal IP address
#       port: 9093
#       protocol: TCP
#       # Routes requests to port 9093 of the Alertmanager StatefulSet Pods
#       targetPort: 9093
#   selector:
#     k8s-app: alertmanager
#   type: "ClusterIP"
