kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: prometheus
  name: alertmanager-pvc-v1
spec:
  storageClassName: alertmanager-db-class-v1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: prometheus
  name: alertmanager-db-class-v1
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
parameters:
  type: pd-standard
  replication-type: none