# apiVersion: v1
# kind: Service
# metadata:
#   name: monitoramento-prometheus
#   namespace: prometheus
#   labels:
#     k8s-app: prometheus
#     app.kubernetes.io/name: monitoramento
#     app.kubernetes.io/component: prometheus
# spec:
#   ports:
#   - name: http-port
#     port: 80
#     protocol: TCP
#     targetPort: 9090
#   selector:
#     k8s-app: prometheus
#   type: LoadBalancer
#   loadBalancerSourceRanges:
#     - 0.0.0.0/0
---
apiVersion: v1
kind: Service
metadata:
  name: monitoramento-prometheus
  namespace: prometheus
  labels:
    k8s-app: prometheus
    app.kubernetes.io/name: monitoramento
    app.kubernetes.io/component: prometheus
spec:
  ports:
  - name: http-port
    port: 9090
    targetPort: 9090
  selector:
    k8s-app: prometheus
  sessionAffinity: None
  type: ClusterIP

