# apiVersion: v1
# kind: Service
# metadata:
#   name: monitoramento-grafana
#   namespace: prometheus
#   labels:
#     k8s-app: grafana
#     app.kubernetes.io/name: monitoramento
#     app.kubernetes.io/component: grafana
# spec:
#   ports:
#   - name: http-port
#     port: 80
#     protocol: TCP
#     targetPort: 3000
#   selector:
#     k8s-app: grafana
#   type: LoadBalancer
#   loadBalancerSourceRanges:
#     - 0.0.0.0/0

apiVersion: v1
kind: Service
metadata:
  name: monitoramento-grafana
  namespace: prometheus
  labels:
    k8s-app: grafana
    app.kubernetes.io/name: monitoramento
    app.kubernetes.io/component: grafana
spec:
  ports:
  - name: http-port
    port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    k8s-app: grafana
  sessionAffinity: None
  type: ClusterIP

